version: '3.5'
services:
  postgres:
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'local'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - ${PWD}/db/postgres:/var/lib/postgresql/data/pgdata

  redis:
    ports:
      - 6379:6379

  mailer:
    ports:
      - 8025:8025
  
  arena:
    build:
      dockerfile: ./Dockerfile
      context: ./docker/arena
    ports:
      - 4567:4567
    environment:
      REDIS_HOST: 'redis'
      REDIS_PASSWORD: ''
      REDIS_PORT: '6379'
      APP_QUEUE: 'trip;acquisition;policy;carpool;normalization;campaign'
    networks:
      - back
    
  dashboard:
    build:
      dockerfile: ./docker/dashboard/Dockerfile
      context: .
    volumes:
      - ${PWD}/dashboard:/app/dashboard
      - ${PWD}/docker/dashboard/ci.env.js:/app/dashboard/src/assets/env.js:ro
      - ${PWD}/shared:/app/shared:ro
    tty: true
    labels:
      - 'traefik.http.services.dashboard.loadbalancer.server.port=4200'

  
  api:
    build:
      dockerfile: ./docker/api/Dockerfile
      context: .
    environment:
      PORT: 8080
      APP_RATE_LIMIT_MAX_FACTOR: '0'
      DEBUG: 'api'
      APP_POSTGRES_URL: postgres://postgres:postgres@postgres:5432/local
    volumes:
      - ${PWD}/api:/app/api
      - ${PWD}/shared:/app/shared:ro
    command: 'sh -c "pm2-runtime start pm2-api.json | pino-pretty"'
    tty: true

  cms:
    build:
      dockerfile: ../docker/cms/Dockerfile
      context: ./cms
    volumes:
      - ${PWD}/cms/config:/opt/app/config
      - ${PWD}/cms/src:/opt/app/src
      - ${PWD}/cms/package.json:/opt/package.json
      - ${PWD}/cms/package-lock.json:/opt/package-lock.json
    ports:
      - "1337:1337"
    environment:
      NODE_ENV: dev
      DATABASE_NAME: local

  worker:
    build:
      dockerfile: ./docker/api/Dockerfile
      context: .
    volumes:
      - ${PWD}/api:/app/api
      - ${PWD}/shared:/app/shared:ro
    command: 'sh -c "pm2-runtime start pm2-worker.json | pino-pretty"'
    tty: true 
    environment:
      DEBUG: 'worker'
      APP_POSTGRES_URL: postgres://postgres:postgres@postgres:5432/local

  s3:
    ports:
      - 9000:9000

networks:
  front:
  back:
