default:
  target: "local"
  outputs: 
    local:
      type: postgres
      threads: 1
      host: localhost
      port: 54321
      user: "{{ env_var('DBT_DB_USER', 'postgres') }}"
      password: "{{ env_var('DBT_DB_PASSWORD', 'postgres') }}"
      dbname: "{{ env_var('DBT_DB_NAME','demo') }}"
      schema: "{{ env_var('DBT_DB_SCHEMA', 'stats') }}"

