name: Deploy frontends (public)
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy ${{ matrix.project_name }}
    strategy:
      matrix:
        env: [demo, production]
        project_name: [public]
        include:
          - project_name: public
            build_directory: public
            build_command: |
              NODE_OPTIONS=--openssl-legacy-provider npm run build
            dist_directory: public/out
            bucket_name_var: PUBLIC_BUCKET_NAME
            cache_dependency_path: public/package-lock.json
    environment: ${{ matrix.env }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ${{ matrix.cache_dependency_path }}

      - name: Install and Build 🔧
        env:
          DEPLOY_ENV: ${{ matrix.env }}
        run: |
          cd ${{ matrix.build_directory }}
          npm ci
          ${{ matrix.build_command }} 

      - name: Deploy to bucket
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ vars[matrix.bucket_name_var] }}
          AWS_ACCESS_KEY_ID: ${{ secrets.BUCKET_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.BUCKET_SECRET_KEY }}
          AWS_S3_ENDPOINT: ${{ vars.BUCKET_ENDPOINT }}
          AWS_REGION: ${{ vars.BUCKET_REGION }}
          SOURCE_DIR: ${{ matrix.dist_directory }}
